<a href="https://colab.research.google.com/github/ucfilho/AI/blob/main/AI_2023/ANN_regression/ANN_polymer_deserability_may_19_2021.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# bibliotecas usadas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing
from sklearn.metrics import r2_score
from google.colab import files
from scipy import optimize

In [ ]:
# para gerar o grafico no browser
%matplotlib inline

In [ ]:
!git clone https://github.com/ucfilho/ANN_2021_01
%cd ANN_2021_01

Cloning into 'ANN_2021_01'...
remote: Enumerating objects: 538, done.
remote: Counting objects: 100% (169/169), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 538 (delta 85), reused 164 (delta 80), pack-reused 369
Receiving objects: 100% (538/538), 80.06 MiB | 30.26 MiB/s, done.
Resolving deltas: 100% (294/294), done.
Updating files: 100% (77/77), done.
/content/ANN_2021_01


In [ ]:
df=pd.read_csv("Polimero_maio_21_2015.txt",sep='\t')
print(df.head())

   Time     TC     Y  MI    MW
0  80.0  170.0  76.5  62  2940
1  80.0  180.0  77.0  60  3470
2  90.0  170.0  78.0  66  3680
3  90.0  180.0  79.5  59  3890
4  85.0  175.0  79.9  72  3480


In [ ]:
# separa os dados em normatizados e originais
X = df[['Time','TC']]
y = np.array(df[['Y','MI','MW']]).reshape(-1,3)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.10, shuffle=True, random_state=3)

In [ ]:
scaler_X = preprocessing.MinMaxScaler((-1,1)).fit(X)
scaler_Y = preprocessing.MinMaxScaler((-1,1)).fit(y)

In [ ]:
X_train = scaler_X.transform(X)
y_train = scaler_Y.transform(y)

In [ ]:
'''
X_train = scaler_X.transform(X_train)
X_test = scaler_X.transform(X_test)
y_train = scaler_Y.transform(y_train)
y_test = scaler_Y.transform(y_test)
'''

'\nX_train = scaler_X.transform(X_train)\nX_test = scaler_X.transform(X_test)\ny_train = scaler_Y.transform(y_train)\ny_test = scaler_Y.transform(y_test)\n'

In [ ]:
# define a rede neural
model = MLPRegressor(solver='lbfgs',activation='tanh',alpha=1e-5,hidden_layer_sizes=(15),
                     random_state=1)

In [ ]:
# treina a rede neural
model.fit(X_train, y_train)

MLPRegressor(activation='tanh', alpha=1e-05, hidden_layer_sizes=15,
             random_state=1, solver='lbfgs')

In [ ]:
# https://www.itl.nist.gov/div898/handbook/pri/section5/pri5322.htm

In [ ]:
# usa a rede neural treina em calculos para treino e teste
y_calc_train=model.predict(X_train)
# y_calc_test=model.predict(X_test)

In [ ]:
y_train

array([[-0.61702128, -0.33333333, -1.        ],
       [-0.40425532, -0.6       ,  0.11578947],
       [ 0.0212766 ,  0.2       ,  0.55789474],
       [ 0.65957447, -0.73333333,  1.        ],
       [ 0.82978723,  1.        ,  0.13684211],
       [ 1.        ,  0.6       , -0.45263158],
       [ 0.87234043,  0.46666667, -0.01052632],
       [ 0.74468085,  0.73333333, -0.26315789],
       [ 0.78723404,  0.86666667,  0.17894737],
       [ 0.19148936,  0.46666667, -0.11578947],
       [-1.        ,  0.86666667, -0.83157895],
       [ 0.23404255, -0.86666667,  0.45263158],
       [-0.40425532, -1.        , -0.55789474]])

In [ ]:
y_calc_train

array([[-0.61738232, -0.33337197, -0.99994229],
       [-0.40518786, -0.6007252 ,  0.11588197],
       [ 0.02124032,  0.1998564 ,  0.55803901],
       [ 0.65943924, -0.73403266,  1.000044  ],
       [ 0.8468796 ,  0.73325763, -0.08216555],
       [ 0.8468796 ,  0.73325763, -0.08216555],
       [ 0.8468796 ,  0.73325763, -0.08216555],
       [ 0.8468796 ,  0.73325763, -0.08216555],
       [ 0.8468796 ,  0.73325763, -0.08216555],
       [ 0.19120349,  0.46726165, -0.11548114],
       [-1.00007076,  0.86713072, -0.83124186],
       [ 0.23475845, -0.8659042 ,  0.45243359],
       [-0.40417703, -1.00017644, -0.55811518]])

In [ ]:
# transforma dos dados calculados na forma original (nao normatizado)
y_obs_train=scaler_Y.inverse_transform(np.array(y_train).reshape(-1,3))
# y_obs_test=scaler_Y.inverse_transform(np.array(y_test).reshape(-1,3))
y_calc_train=scaler_Y.inverse_transform(y_calc_train.reshape(-1,3))
# y_calc_test=scaler_Y.inverse_transform(y_calc_test.reshape(-1,3))

In [ ]:
'''
mse=mean_squared_error(y_obs_test,y_calc_test)
print("MSE teste=",mse)
R2=r2_score(y_obs_test,y_calc_test)
print("R^2 teste=",R2)
'''

'\nmse=mean_squared_error(y_obs_test,y_calc_test)\nprint("MSE teste=",mse)\nR2=r2_score(y_obs_test,y_calc_test)\nprint("R^2 teste=",R2)\n'

In [ ]:
mse=mean_squared_error(y_obs_train,y_calc_train)
print("MSE treino=",mse)
R2=r2_score(y_obs_train,y_calc_train)
print("R^2 treino=",R2)

MSE treino= 1685.3920755346742
R^2 treino= 0.9629146653266748


In [ ]:
def MW_calc(x_test): #Time     TC     Y  MI    MW
    global Y_OLD,model
    x_test = np.array(x_test).reshape(-1,2)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,3))
    y =  y_calc_test[:,2]
    return y
def MI_calc(x_test):
    global Y_OLD,model
    x_test = np.array(x_test).reshape(-1,2)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,3))
    y =  y_calc_test[:,1]
    return y
def Y_calc(x_test):
    global Y_OLD,model
    x_test = x_test.reshape(-1,2)
    y_calc_test=model.predict(x_test)
    y_calc_test =scaler_Y.inverse_transform(y_calc_test.reshape(-1,3))
    y =  y_calc_test[:,0]
    return y

def Desirability(y,U,T,L):
    if y<L:
        d=0
    if (y>=L)&(y<=T):
        d=(y-L)/(T-L)
    if (y>=T)&(y<+U):
        d=(U-y)/(U-T)
    if (y>U):
        d=0
    return d

In [ ]:
def function(x):
    Time=x[0]
    TC=x[1]
    MW=MW_calc(x)
    MI=MI_calc(x)
    Y=Y_calc(x)
    U=3890
    T=3400
    L=2940
    d1=Desirability(MW,U,T,L)
    U=68
    T=65
    L=62
    d2=Desirability(MI,U,T,L)
    U=80
    T=77.5
    L=75.6
    d3=Desirability(Y,U,T,L)
    fun = (-1)*(d1*d2*d3)**(1/3)
    return fun

In [ ]:
bounds = [(-1, 1),(-1, 1)]

Condicoes = optimize.differential_evolution(function,bounds,
                                      init="latinhypercube", # obs: init="random"
                                      maxiter=100, popsize=50,recombination=0.5)

x_opt = Condicoes.x
x_opt =scaler_X.inverse_transform(np.array(x_opt).reshape(-1,2))
y_opt =model.predict(x_opt)
y_opt =scaler_Y.inverse_transform(np.array(y_opt).reshape(-1,3))
print(x_opt)
print(y_opt)

[[ 87.38361656 170.49947359]]
[[  72.73293761   60.14936428 3852.59516626]]



PS: no planejamento de experimentos utilizando o Statistica -e-papers Y=80 MI=65,044 MW=3586,1

tempo=86,65 e Temperatura=178,77